### ISSUE TITLE
Cannot input the Chinese characters in the table

### ISSUE THREAD

**Issue by netvolcano** [nocodb/nocodb#1294]
NocoDB used as docker : true 
NocoDB version :  the latest version 
Database used in NC_DB URL  : mysql 
Project was created  by clicking : New Project
Database on which spreadsheet is created : mysql
OS on which NocoDB is running :  WSL Ubuntu 20.04 LTS
Node.js version if running as node : 
Database version : mysql 5.7

**Steps To Reproduce**
1. Create a new table.
2. Add a new line.
3. If I input some Chinese characters into the table cell, there will be a red box with warning. I can not modify it into Chinese characters.
4.  If I try to edit the table column title and rename it to a Chinese character name, it will say "Name should start with an alphabet or _". After that, I can not finish the renaming.  

**Expected behavior**
I want to input Chinese characters into the table.

**Screenshots**
![image](https://user-images.githubusercontent.com/89053282/154495316-93171a56-a3f8-42d2-91ad-86559e6513c3.png)

Join our discord : https://discord.gg/5RgZmkW for realtime help.

Node version : **v12.22.1**
Arch type: **x64**
Platform: **linux**
Docker: **true**
Database: **sqlite3**
packageVersion: **0.9.27**

**Comment by netvolcano** [comment]
I have tried to set the characters to UTF8MB4 in the MySQL, but the issue is still here. Is it a bug?

**Comment by dstala** [comment]
> 

@netvolcano Currently at NocoDB, we have kept constraints for column name creation common for both REST & GQL. GQL limits the use of characters in column names
http://spec.graphql.org/June2018/#Name

We will explore best way to allow extended character set when configured for REST API's

**Comment by netvolcano** [comment]
@dstala :  Thank your replying. I found this issue was not only in the column names but also in the table cells. I hope this issue will be solved in future.

**Comment by wingkwong** [comment]
@netvolcano If you want to input characters with `UTF8MB4` **in the cell**, then you need to configure it in DB. However, if you want to input it in table name or column name. There will be two cases. 

**Case 1: You are using REST APIs**

For this case, it works as expected.

<img width="479" alt="image" src="https://user-images.githubusercontent.com/35857179/157593890-a79c955c-aed5-4732-a8c9-87a93b4393b9.png">

**Case 2: You are using GraphQL APIs**

I believe this issue belongs to this case. You are expected to see `Name should start with an alphabet or _` because _names in GraphQL are limited to this ASCII subset of possible characters to support interoperation with as many other systems as possible_ (See the link in Raju's reply). 

As this is the design from GraphQL side, I'd suggest you to use the ASCII subset for naming your tables or columns. There won't be any fix like mapping Chinese names to a ASCII subset as it's computationally expensive.

**Comment by netvolcano** [comment]
@wingkwong : Can you show your docker compose file for DB or give me some examples to configure th DB? I found the default docker compose file of the nocodb would not support 'UTF8MB4'.

**Comment by wingkwong** [comment]
@netvolcano Take this as a reference. 

https://github.com/nocodb/nocodb/blob/e57c56b2cda7777fb76605d170f18413ff3061a8/docker-compose/mysql/docker-compose.yml#L11

Once again, I want to point out that **you cannot use Chinese characters when naming tables or columns if you are using GraphQL APIs**.
