### ISSUE TITLE
Feature : Support Kanban view

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#140]
- Meta DB Migration Script
  - two new columns in `nc_kanban_view_v2` 
    - `grp_column_id`: grouping field column id (used in stackedBy)
    - `meta`: meta data like stack order, colors, option titles etc.
- stackedBy in Toolbar
  - dropdown for selecting a Single Select column
  - rerendering kanban view based on the change
- Kanban View
  - Basic View Operations
    - Create View
    - Copy View
    - Rename View  
    - Delete View
  - Stack 
    - Create a new Stack 
    - Re-order Stack
    - Add records within a Stack
      - Preset grouping field value
    - Drag-and-drop record cards to other Stack
    - Scroll to fetch records
    - Dropdown
      - Add new record
      - Collapse Stack
      - Delete Stack
  - Record Card
    - Click to expand form to edit
    - Drag-and-drop records across stacks
  - Share View 
  - Misc
    - Sync grouping field options from other views (e.g. remove options in grid view)
  - Cypress

**Comment by grepler** [comment]
When this is implemented, these are the features I'd love to see:

1) 'swimlanes' option, so that we can separate out columns by a multi-select / single-select field dimension.
   for reference, consider something similar to: https://ej2.syncfusion.com/vue/demos/#/bootstrap5/kanban/swimlane-template.html

2) show configurable field data on the cards
  for additional context, something similar to: https://ej2.syncfusion.com/vue/demos/#/bootstrap5/kanban/card-template.html


3) same card in multiple lanes, columns:
   control + click and drag to split a card and add to a multi-select field (cards with multiple values in a multi-select field should appear in multiple areas).

**Comment by zacker330** [comment]
Hi guys, Is this feature implemented? I can't find out it in the releases list.

**Comment by TechMasterElvy** [comment]
I am confused, I setup heroku and isntalled nocodb and studied the docs only to find no kanban, gantt or calendar is there thought it's shown in demos and on the website!

You could've at least added "Coming Soon"

**Comment by nilsreichardt** [comment]
@o1lab I saw that https://github.com/nocodb/nocodb/pull/903 is merged 🎉  Is there a timeline when we can expect the kanban view feature?

**Comment by khan95osu** [comment]
Agreed. The website shows a calendar and Kanban but it's not available for me

**Comment by matthewblott** [comment]
Lads, this is your homepage!

![Screenshot 2022-05-07 at 20 04 41](https://user-images.githubusercontent.com/1231417/167268483-5fbb0094-ffe1-4ed8-a243-dfc294a7eae5.jpg)

**Comment by wingkwong** [comment]
Some contents in main website are outdated and we're revamping the website. The outdated content will be removed in the next release. Sorry for any inconvenience caused.

**Comment by zhangshengping** [comment]
is there some schedule for kanban view?
I really want this feature!

**Comment by matbgn** [comment]
Hi @wingkwong and @o1lab 

As I see on your Roadmap on Github this feature is the most awaited one in the Backlog do you have any time frame or plans for it? 

Moreover @wingkwong already started a MR but what has happen with it since then?

The idea is more to know on which Airtable alternative project is it better to invest/contribute, e.g. in comparison with https://github.com/bram2w/baserow

Many thanks for your feedback

**Comment by apprentiLAB-Suzanne** [comment]
@matbgn for info Baserow is not completely open source, there are features they reserve for premium users (like kanban view).

**Comment by matbgn** [comment]
> @matbgn for info Baserow is not completely open source, there are features they reserve for premium users (like kanban view).

+1 totally agree but there are others actively working on it like AppFlowy, AnyTime (will be OSS on release), FocalBoard, etc. so the question is where should we put investment as a community

**Comment by Ujwal100000** [comment]
Kanban View- How do I add Grouping Field ? Its not automatically updated

**Comment by wingkwong** [comment]
> Kanban View- How do I add Grouping Field ? Its not automatically updated

You need to create a SingleSelect column in your table. Other column types are not supported to be a grouping field.
