### ISSUE TITLE
SingleSelect in Column Type Can't Add option

### ISSUE THREAD

**Issue by ninjagang** [nocodb/nocodb#1423]
NocoDB used as docker : false
NocoDB version : v0.84.14
Database used in NC_DB URL  : mysql
Project was created  by clicking : New Project
Database on which spreadsheet is created : mysql
OS on which NocoDB is running : debian 11
Node.js version if running as node : v12.22.5
Database version : MariaDB 10.5

I have Created a Table with Singleselect Column Type (5 options)， now I want to add or delete some options，when i click "save"，it pop message :"update table failed"

**Comment by dstala** [comment]
@ninjagang 
currently, if the option is already in use by a record - attempt to edit (rename or delete) that option fails.

**Comment by wingkwong** [comment]
To supplement a bit, when you update the options, it's actually updating the datatype (enum) in MYSQL. If the option is being used, you are expected to get `Data truncated for column XXX at row 1` due to datatype mismatch.

Therefore, as long as the option is not being used. adding or deleting is working fine. Otherwise, you need to remove the target option from the data first.
