### ISSUE TITLE
Unable to upload .xlsx file

### ISSUE THREAD

**Issue by wuhaohao1234** [nocodb/nocodb#1851]
Because our company's translators are not developers, they use excel sheets, and they want to upload excel sheets

**Comment by wuhaohao1234** [comment]
And the title of their table is Chinese, which also contains a lot of Chinese

**Comment by wuhaohao1234** [comment]
They use Chinese software: wps

**Comment by wuhaohao1234** [comment]
cannot read properties of undefined

**Comment by wingkwong** [comment]
@wuhaohao1234 

**Please enter the following details**

Copy and paste project info : [Youtube Video](https://www.youtube.com/watch?v=AUSNN-RCwhE)

Example: 

Node version : **v12.22.1**
Arch type: **x64**
Platform: **linux**
Docker: **true**
Database: **sqlite3**
packageVersion: **0.9.27**

or 

please provide the following details :
NocoDB used as docker : true / false
NocoDB version : 
Database used in NC_DB URL  : mysql | pg | mssql | sqlite3 / (defaults to sqlite3 if empty)
Project was created  by clicking : New Project | New Project by connecting to external database
Database on which spreadsheet is created : mysql | pg | mssql | sqlite3 / (defaults to sqlite3 if empty)
OS on which NocoDB is running : 
Node.js version if running as node : 
Database version : 

**Steps To Reproduce**
1. Go to '...'
2. Click on '....'
3. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Comment by wingkwong** [comment]
Excel Import is back in latest version. Please try in `0.90.11`. Feel free to reopen if you have further issue.

**Comment by ovizii** [comment]
> Excel Import is back in latest version. Please try in `0.90.11`. Feel free to reopen if you have further issue.

can you please describe or screenshot where the excel import is located? 
not meaning to complain but you guys keep hiding / reshuffling the menus a lot. I just spent 30 minutes desperately looking for the import from excel function and this thread is my only hint.

**Comment by wingkwong** [comment]
@ovizii My apologies for making the wrong statement as I just realised that the excel import changes are still in review and has been released yet. The excel import option will be available in New Project menu. Will include the screenshots in the document for the next release.

**Comment by ovizii** [comment]
thank you so much for eliminating my confusion :-)

**Comment by iAndroS** [comment]
Also import from excel file does not work. The table columns are being parsed, but after pressing the IMPORT button, the page is simply updated, there is no table in the interface.

Node: **v16.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **sqlite3**
PackageVersion: **0.104.2**

**Comment by wingkwong** [comment]
@iAndroS Please create a new issue and attach a sample excel file for reproducing the issue if possible.
