### ISSUE TITLE
Postgres: can only access public schema

### ISSUE THREAD

**Issue by Eliagandolfi** [nocodb/nocodb#226]
When I connect a project to a Postgres database (no matter if hosted locally or remotely on AWS), I can only see tables in the public schema.
How do I access tables in other schemas?

I'm sure the credentials I'm using have full admin access to all schemas

**Comment by o1lab** [comment]
Please check this out https://www.youtube.com/watch?v=rS0NRwRCjx0

**Comment by o1lab** [comment]
We allow to edit the connection json under the hood while connecting to database. Please close this if it resolves.

**Comment by pranavxc** [comment]
Related to #187

**Comment by willduarte** [comment]
There is a way to import multiple schemas? Because the `searchPath` logic is to find the first occurrence inside the database. ([docs](https://www.postgresql.org/docs/9.6/ddl-schemas.html#DDL-SCHEMAS-PATH))

> The first matching table in the search path is taken to be the one wanted. If there is no match in the search path, an error is reported, even if matching table names exist in other schemas in the database.

**Comment by pranavxc** [comment]
> There is a way to import multiple schemas? Because the `searchPath` logic is to find the first occurrence inside the database. ([docs](https://www.postgresql.org/docs/9.6/ddl-schemas.html#DDL-SCHEMAS-PATH))
> 
> > The first matching table in the search path is taken to be the one wanted. If there is no match in the search path, an error is reported, even if matching table names exist in other schemas in the database.

Currently, it's not possible to access different schema in a single project, you have to create different projects for each one.

**Comment by akrea** [comment]
Hi
In the latest revision of the UI it is not possible (or at least I did not figure out how) to connect to a specific schema. Can you help me out with this?

As a further note: We do integrate nocodedb in an existing database. nocodb writes its core data into the public schema. It would be really helpful to be able to tell nocodb to use a specific nocodb-Schema so that the public schema remains pristine for other project related table that really need to be in public schema.

Thank you for your efforts.
