### ISSUE TITLE
[Feature] Cell Display Options

### ISSUE THREAD

**Issue by Cirsten** [nocodb/nocodb#2287]
**Need for this feature**
This is for appareances. A realy long string of text or many items in"multipleselect" greatly changes the appearnce of a table, and the full content of this is not always needed at first glance (sometimes it is)

**Describe the solution you'd like**
Supply options for cell display, ie "truncated" to fit the determined cell width, "text wrap" will display entire text and increase row height (current only option)

**Describe alternatives you've considered**
None. Only sollution would be less content which is not a solution

**Additional context**
These option are available in excel as a referrence

**Comment by o1lab** [comment]
Can be looked into with select/multi-select implementation. We would like to keep it simple - truncate it. And on hover we can show the full value.

**Comment by Cirsten** [comment]
Would this be applied to other column types too?

See http://siabodsmarvelcomicpage.weebly.com/test.html to compare how Airtable presents the almost the same info

I find much easier to follow when those columns are truncated too

**Comment by mertmit** [comment]
I will implement this into multiselect column as an option and I will check to see which other column types are suitable. Thank you for your suggestion.

**Comment by from-nibly** [comment]
I would say every column needs this, and possibly as a table option to set word wrap off for every column. I am only able to see like 1/3 of my rows because one column has word wrap.

**Comment by Rafurus** [comment]
I found that we have 2 other issues similar to this one:
1. https://github.com/nocodb/nocodb/issues/831
2. https://github.com/nocodb/nocodb/issues/345

This problem is still alive and it's affects all column types. 
Setting fixed height for rows and tructated them will be good. 

Quick sample:
![obraz](https://user-images.githubusercontent.com/12428720/203815725-4a914981-b063-4caf-9045-003adb3d0a46.png)
