### ISSUE TITLE
[Feature] Visual distinction between NULL and empty string

### ISSUE THREAD

**Issue by pauljura** [nocodb/nocodb#2409]
**Need for this feature**
If I have a table with a text column that can have NULLs, there is nothing to indicate the difference between a NULL and an empty string. It would be nice to have something that explicitly states when a value is NULL. It could be subtle, so that a table full of NULL values doesn't look busy and crowded. It should also look distinct from an actual string, so nobody could confused it with the literal string "NULL". For example, something like the word "null" (or just the letter "N") in a light muted colour, and italicised, could work well.

**Comment by o1lab** [comment]
Light muted color makes sense.

**Comment by zblesk** [comment]
That would still visually clutter the table, though. 

Somewhat related to that: For the common use cases (that primarily involve users looking at tables and working with them, instead of writing sql queries) I think it would work better to tweak the _handling_ of nulls. 

For instance: right now, if I create a filter in my view, select a string column, and filter by 'is null', I receive 300 rows. If I change that to 'is empty', I get 0. 
I presume that's caused by the distinction between "" and null in the DB; but no common user will understand that, and will instead wonder why these clearly empty cells don't fall under 'is empty'. 

(Not to mention that I often want exactly that - 'show me which fields do not have a value'. As it is, I have to make a disjunctive filter to get both, which is annoying, _and_ makes more complicated queries impossible. (Unless there _is_ a way to parenthesize expressions I haven't discovered yet.) 

Eh, I guess it depends on what the desired user base for NocoDB is. Just thinking out loud here.

**Comment by pauljura** [comment]
It's only "clutter" if you don't understand or care about the distinction. Or if you have a random mix of "" and NULLs, in which case I would argue it's good to see the inconsistency so you can correct it.

It comes down to the audience. If your audience is non-technical and only using Nocodb as an enhanced spreadsheet, then sure, they might not care. But they may not have any NULLs anyway.

On the other hand, my use case is to expose views of several pre-existing databases, without having to code a UI specifically for this, and without exposing database credentials. We are are developers and analysts, and the distinction between "" and NULL is meaningful to us, and therefore important to see. I hope I'm not the exception here, because Nocodb seems like the ideal solution for us, and I can imagine more tech-savvy people using it the same way.

In any case, it should be easy to make the display sufficiently subtle as to not be "clutter", while still being useful for those that need it.

Also, it's funny you mention:

> I presume that's caused by the distinction between "" and null in the DB; but no common user will understand that, and will instead wonder why these clearly empty cells don't fall under 'is empty'.

I'll take this as support for the feature request, because the distinction would be obvious if users could clearly see which cells were NULL and which were "" 😉

**Comment by zblesk** [comment]
> It comes down to the audience. 

Yes, exactly. I mean, I don't disagree with most of what you're saying, except maybe the last one. 😁
It seems you can't create complex filters in NocoDB. So if you want to express something like "Select books that have less than 100 pages, or their title is empty", you can't. (Because you need to do a `pages <100 & (title is null || title is empty)`. I'd argue that it's a pretty common use case, and adding a true 'does not contain data' operator is probably less work than fully supporting nested expressions... 
(Not to mention I find the idea of Common Joe knowing what the mysterious 'nulls' mean and what the difference between them and just empty cells is, a bit optimistic. Again, matter of the intended audience.)

I guess that it's also off topic in this thread, so I'll drop it. Thanks for sharing your thoughts. 🙂
