### ISSUE TITLE
Consider dropping the requirement for specific characters in passwords

### ISSUE THREAD

**Issue by yurkobb** [nocodb/nocodb#242]
The current sign up form requires "Atleast (sic) 8 letters with one Uppercase, one number and one special letter".

[Per NIST](https://pages.nist.gov/800-63-3/sp800-63b.html), requiring specific character types in a password is not recommended (emphasis mine):

> __Verifiers SHOULD NOT impose other composition rules (e.g., requiring mixtures of different character types or prohibiting consecutively repeated characters) for memorized secrets.__ Verifiers SHOULD NOT require memorized secrets to be changed arbitrarily (e.g., periodically). However, verifiers SHALL force a change if there is evidence of compromise of the authenticator.

I think the present requirement actually lowers the entropy of resulting passwords by effectively making them shorter (it's harder to remember a short `p@ssw0rd`-style password than a longer `passphrases are better`-style one).

![Screenshot 2021-06-07 at 09-58-56 Sign Up Noco](https://user-images.githubusercontent.com/479389/120975976-8cf90680-c77a-11eb-9afc-e9a492a6e8ae.png)

**Comment by bannmann** [comment]
In case you need some background on why some people like "passphrase" style passwords, please see https://security.stackexchange.com/questions/6095/xkcd-936-short-complex-password-or-long-dictionary-passphrase

To improve the advice given by the NocoDB UI, how about integrating [zxcvbn](https://github.com/dropbox/zxcvbn)? It's a nice client-side JS developed by Dropbox Inc that determines the following scores:
`p@ssw0rd` - 0 of 4
`Password1!` - 1 of 4
`PasswordPasswordPasswordPassword1!` - 1 of 4
`Tr0ub4dour&3` - 2 of 4
`CrockParishEngrossCopied` - 4 of 4
Try the [online demo](https://lowe.github.io/tryzxcvbn/).

**Comment by OmgImAlexis** [comment]
>  (it's harder to remember a short p@ssw0rd-style password than a longer passphrases are better-style one).

It's 2021, you should all be using password managers. End of story.

@bannmann read the above.

**Comment by bannmann** [comment]
> > (it's harder to remember a short p@ssw0rd-style password than a longer passphrases are better-style one).
> 
> It's 2021, you should all be using password managers. End of story.

@OmgImAlexis: using password managers does not change anything about the entropy properties of the chosen password. And brute force attacks on passwords, whether online or offline, are simpler if you know all the passwords will have a certain combination of character types. That's the main reason that as of 2017, NIST _explicitly recommends **not** having password composition rules_ (see the link in @yurkobb's post).

So much for the cryptography/security rationale.

----

Now let's look at usability:

I dislike being forced to use special characters even though I *am* using a password manager. The reason is that I sometimes use devices where that password manager is not installed (e.g. an incognito browser tab on my work computer). In that case, I find it nice to be able to locate the password in the password manager on my mobile phone, look at it once, then quickly type in the six words on the other device.

With the "classic" password composition rules, "transcribing" a password in this manner often means looking back and forth between the devices several times. Also, if the other device happens to be a mobile phone, passwords having special characters and even uppercase/lowercase variations result in having to switch keyboard modes all the time.

----

Sure, people may not agree with my opinion on usability, or with my and @yurkobb's preference for passphrase style passwords. That's fine. All I'm saying is that personal preference alone is usually not a good rationale for design choices in software that actively contradict industry standards/best practices and/or weaken the cryptographic strength of passwords.
