### ISSUE TITLE
vue3 : Home / ProjectList

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#2628]
- [ ] Project list - table view
     -  [ ] Pagination
     -  [ ] Reload
     -  [ ] Filter
     -  [ ] Edit
     -  [ ] Delete 
     -  [ ] Create button
- [ ] Project with external database connection
     -  [ ] Test connection
     -  [ ] SSL file upload option
     -  [ ] Schema select option for pg and mssql
     -  [ ] Validations
     -  [ ] Monaco editor for custom JSON
- [ ] Xcdb project creation page
- [ ] Project title edit page

**Comment by o1lab** [comment]
The idea is to make our vue3 project list page similar to this with grid and icon view.

<img width="940" alt="Screenshot 2022-07-11 at 10 54 42" src="https://user-images.githubusercontent.com/5435402/178238950-27dd3d9c-9690-469b-9f4d-6e46d3339fd0.png">

**Comment by bcakmakoglu** [comment]
Technically it's done, though the sidebar lacks actual navigation.

Should there be a new issue that clarifies what exactly is supposed to happen on each navigation item? @o1lab

**Comment by o1lab** [comment]
Cool, @pranavxc had changes related to side navbar behaviour. We would need new set of APIs and schema migrations.

Recent : is recently accessed.
Starred : is like bookmarked.
Shared with me : is where it gets tricky. I believe - we had solved that.

@pranavxc can take this up once we are kinda ready with spreadsheet ?

**Comment by o1lab** [comment]
UI changes
- [ ] Let's only have list view like before - given the time constraint
  - [ ] Need search
  - [ ] Need pagination
  - [ ] Remove updated_at - as we do no really update that field on update of project
- [ ] Swap delete and edit options in order. first should be edit
- [ ] Rename Edit button to Save in 'Edit project' modal
- [ ] Remove * before Inflection - Table name in connect extDB modal. we have default value for this set, so user needn't worry about it much
- [ ] edit connection json is looking like a pre filled text box; make it look like a button (like submit/test-connection)

**Comment by dstala** [comment]
Issues

- [ ] Edit project modal accepts blank name; need a validator
- [ ] Project name can be a blank space; good to add a validator requesting some alphanumeric characters
- [ ] ExtDB accepts space as a project name (and any name starting from space). Fails during Test connection
- [ ] Delete project popup message: Do you want to delete project <project-name>? . Would be good to add a more intense warning. the pop-up looks suttle
- [ ] Provide default name for xcdb project.
- [ ] After clicking on one of options for creating a project, pressing the ESC key should bring you back to the project page. OR provide a back logo-based button somewhere on top. took a while for me to realize I can click NC logo to go back
- [ ] Error: create ext-DB project, give project name with 50 characters (xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx). I think this is because the database name exceeds 50 characters as we add noco_ suffix.

- [ ] List view: `Title` overflows over `Updated at`
![Screenshot 2022-07-20 at 10 45 17 PM](https://user-images.githubusercontent.com/86527202/180043091-c2607792-f028-4a30-b04f-01b284250ad9.png)

- [ ] Ext DB configuration page in Dark mode - text invisible
![Screenshot 2022-07-20 at 10 47 36 PM](https://user-images.githubusercontent.com/86527202/180043413-285af50e-0ce4-48fb-b652-2b1454d1e109.png)

**Comment by o1lab** [comment]
Agreed, we will put back later :D

**Comment by dstala** [comment]
- [ ] Pagination: show an empty skeleton (10 records) even if we have only 2 projects created. This way, pagination info will not move around when we move between pages.
- [ ] Multiple projects with same name are still allowed (during creation as well as rename)
- [ ] [SQLite DB] Delete project throws error
```
projectAclMiddleware :: Forbidden [Error]: projectDelete - user : Not allowed
    at Function.forbidden (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/meta/helpers/catchError.ts:47:11)
    at projectAclMiddleware (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/meta/helpers/ncMetaAclMw.ts:64:17)
    at /Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/meta/helpers/catchError.ts:6:20
    at Layer.handle [as handle_request] (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/express/lib/router/route.js:144:13)
    at authMiddleware (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/meta/helpers/ncMetaAclMw.ts:24:7)
    at /Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/meta/helpers/catchError.ts:6:20
    at Layer.handle [as handle_request] (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/express/lib/router/route.js:144:13)
    at exports.default (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/src/lib/meta/helpers/extractProjectIdAndAuthenticate.ts:141:5)
DELETE /api/v1/db/meta/projects/undefined 403 44 - 30.721 ms
```

**Comment by bcakmakoglu** [comment]
Can this be closed @o1lab @dstala ?
