### ISSUE TITLE
Feature: open user registration

### ISSUE THREAD

**Issue by dismantl** [nocodb/nocodb#284]
I would like to be able to allow open registration for my instance of NocoDB so anyone can create an account. Currently it seems like you need to invite all new users, which makes the "Don't have an account ? Sign Up" link on the sign in page very confusing. When I try to register a new account it gives the error `Not allowed to signup, contact super admin.`

![image](https://user-images.githubusercontent.com/2007008/122134832-60de2500-ce0d-11eb-8db8-687f73a0432f.png)

**Comment by Paolocesareo** [comment]
But was this problem solved in the end?

**Comment by jsanta** [comment]
Having the same issue. The only way to  register new users is by adding them to the team using the admin user and sending them an invitation (but remember before to install and configure the MilSend or the SMTP plugin, otherwise no email will be sent).
If that's the only way there's no sense in having a "Sign up" link on the login page.

Is there a way of enabling this setting? Something like a NC_ENABLE_EXTERNAL_SIGNUP=true environment variable?

**Comment by jsanta** [comment]
Found a dirty workaround (which I don't like):

1. In file: `node_modules/nocodb/dist/bundle.js`
2. find the following string: `if(await this.users.first())return s(new Error("Not allowed to signup, contact super admin."));`
3. and negate the if -> `if(!await this.users.first())` 
4. or add an extra condition which would require setting up an extra variable in your .env file ->` if(await this.users.first() || process.env.NC_ENABLE_SIGNUP)`
5. if you chose to apply step 4 -> edit your .env file and add `NC_ENABLE_SIGNUP=true`

Tested it and works, just remember to install and configure the MailSend or the SMTP plugin, otherwise no email will be sent.
Regards.

**Comment by o1lab** [comment]
Super admin can now toggle whether new signups are allowed or not from the UI

**Comment by erem2k** [comment]
> Super admin can now toggle whether new signups are allowed or not from the UI

Was there any specific reason this was restricted to UI-only path?
Documentation mentions `NC_INVITE_ONLY_SIGNUP` env var existing previously, and this was and still is really helpful for automation purposes i.e. deployment scripts
