### ISSUE TITLE
Vue3: Checkbox Cell

### ISSUE THREAD

**Issue by mustafapc19** [nocodb/nocodb#2875]

**Comment by dstala** [comment]
@mustafapc19 

Changes
- [ ] Would be good to provide basic colour palette in default menu & colour picker in advanced menu (same as v1).
- [ ] [Issue in v1 as well] Checkbox is eventually having 3 values instead of 2. `true`, `false`, `null`; we should have only `true` / `false`;

Verified
- [x] Create checkbox column
- [x] Edit icon
- [x] Edit colour
- [x] Rename column
- [x] Clear cell 
- [x] Delete record 
- [x] Delete column

**Comment by mustafapc19** [comment]
@dstala Checkbox column is done by @wingkwong

**Comment by wingkwong** [comment]
>  Would be good to provide basic colour palette in default menu & colour picker in advanced menu (same as v1).

I put `Checkbox Column` to `Pending` for such reason. However, I think it's already covered in one of the Mert's PR. Once it's merged, I'll move it to `In Testing` and ping you.

**Comment by dstala** [comment]
Sure! My bad - while testing as a bunch on develop, missed this out. :)
