### ISSUE TITLE
vue3: Year Cell

### ISSUE THREAD

**Issue by mustafapc19** [nocodb/nocodb#2884]

**Comment by dstala** [comment]
@mustafapc19 @bcakmakoglu 
- IMO, we should allow manually feed (type) for year cell along with GUI option. Its easy to type 1900 instead of many clicks on UI
- No error toast message on failure to insert
  - select anything less than 1900 on UI (MySQL DB)
  - backend error: "Out of range value for column 'Year' at row 1"
  - v1 displayed error toast message
  - on refresh (v2) - record is not stored in DB

**Comment by pranavxc** [comment]
> @mustafapc19 @bcakmakoglu
> 
> * IMO, we should allow manually feed (type) for year cell along with GUI option. Its easy to type 1900 instead of many clicks on UI
> * No error toast message on failure to insert
>   
>   * select anything less than 1900 on UI (MySQL DB)
>   * backend error: "Out of range value for column 'Year' at row 1"
>   * v1 displayed error toast message
>   * on refresh (v2) - record is not stored in DB

@dstala : API failure error toast is part of the grid view, not part of the cells.
