### ISSUE TITLE
[Feature] Limit attachments

### ISSUE THREAD

**Issue by LucBerge** [nocodb/nocodb#2905]
## Recommending Features

**Need for this feature**
I would like to be able to limite the attachments in a column:

Possibility to limit 
- [ ] The number of attachments to a given number.
- [ ] To allow only specified file formats
- [ ] To refuse only specified file formats
- [ ] To limit the file size

**Describe the solution you'd like**
When editing an attachment column, the limits can be defined.

**Comment by LucBerge** [comment]
Thanks @djmaze. I have added this to the original post

**Comment by wingkwong** [comment]
> To allow only specified file formats
> To refuse only specified file formats

@LucBerge What is the use case for showing both at the same time? Supposedly `Allowed` and `Not Allowed` are two disjoint sets. If one is allowed, then it won't be not allowed, and vice versa. I think we can just show the list of allowed formats (by default all are allowed) so that all unselected formats will be considered as `Not Allowed`. What do you think?
