### ISSUE TITLE
vue3: Percent Column

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#2952]
Percent doesn't exist in v1 but in this [PR](https://github.com/nocodb/nocodb/pull/2581)

**Comment by dstala** [comment]
- percent column- modal is different from other as we bring in default input outside (I kind of like it though)
- the configurations on the cell didn't work (precision, default). that will be under pranav scope? 
- default provisioning currently repeats as default number in main menu and default value in expanded menu

**Comment by mustafapc19** [comment]
@dstala There are some complications integrating this [PR](https://github.com/nocodb/nocodb/pull/2581) since backend part(`conditionV2`) has changed a bit. On discussion with @pranavxc have decided to skip the options for now till gui-v2 is completed. Should we hide new options for percent for now or keep things as it is?

**Comment by dstala** [comment]
@mustafapc19 
let us make all features equivalent to v1 (current master, as is). we can consider rest as enhancements once we have vue2===vue3

**Comment by mustafapc19** [comment]
@dstala In vue2(v1) percentage column has no options and cell is just a `FloatCell`. Taking that path for now 👍 

cc: @wingkwong
