### ISSUE TITLE
vue3: Email Json, Phonenumber, url, time column

### ISSUE THREAD

**Issue by mustafapc19** [nocodb/nocodb#2980]

**Comment by dstala** [comment]
@mustafapc19 

Combined observations 

Email / Phone number
- [ ] Too many toast alerts as we type email address. Trigger validation check only after `enter` key is pressed or after `change in cell focus`

URL
- [ ] v1 did allow storing of `www.google.com`, `google.com` with validation enabled. v2 mandates it to be of format `https://google.com`
- [ ] no error message displayed on validation failure. Just record isn't stored

Time
- [ ] Records for this cell are not persistent; disappear on reload
- [ ] Since we are displaying time in 24H format within cell, would be good if we remove AM/PM and just display 0~23H instead.
  
![Screenshot 2022-08-08 at 10 00 22 PM](https://user-images.githubusercontent.com/86527202/183467457-1d5ce265-8a23-4691-945e-0e53349b0dbc.png)
