### ISSUE TITLE
[Feature] Include google fonts / Prevent fonts to be loaded from google

### ISSUE THREAD

**Issue by berti92** [nocodb/nocodb#3059]
Hello,

could you integrate the fonts in your asset pipeline, so that no fonts will be loaded from Google?

Background: In germany it's not allowed to load fonts from google without asking the user before hand.

Thank you very much for your work. I really like your tool!

**Comment by UbioZur** [comment]
To give some more information about it.

It's not about loading the google font, but the fact that google store the user IP address when loading the font, making google store private data which is against privacy law in many countries (including all the countries in Europe due to GDPR).

https://complianz.io/google-fonts-and-gdpr-does-it-work/

https://blog.runcloud.io/google-fonts-gdpr/

https://thehackernews.com/2022/01/german-court-rules-websites-embedding.html

So yes it would be good practice to store the fonts as an asset to avoid having to ask consent / add the annoying popup.

**Comment by toby-m** [comment]
When running the docker image locally with `NC_DISABLE_TELE=true` I'm also seeing calls to a google tracking endpoint ("gstatic.com/.../cleardot.gif") and a google docs form ("docs.google.com/.../forms/...").

That seems really shady and is definitely not GDPR compliant.

**Comment by o1lab** [comment]
Could you help us with full path on cleardot.gif. We will 've the google form disabled or check what is going on there. That shouldn't be shown.
