### ISSUE TITLE
Vue3: Often don't see Team & Auth tab on login by default

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#3227]
Screenshot just after login

![Screenshot 2022-08-18 at 2 31 04 PM](https://user-images.githubusercontent.com/86527202/185355708-7aa5f028-eae0-4eb9-9fd0-b6b81a9c1edf.png)

**Comment by bcakmakoglu** [comment]
@dstala Shouldn't this page be the default on project load anyway?

Seeing as Team & Auth isn't an actual Tab anymore it would be confusing, in my opinion, to have it be opened on project load.
Or am I missing the Team & Auth Tab, because I can't seem to find an actual Tab for it - only the Modal that can be opened from the Project Menu on the top left.

**Comment by bcakmakoglu** [comment]
I will close this issue as it's resolved for now - the "better" fix will come with a future release then.
