### ISSUE TITLE
Metadata on multi-instance deployment becomes unsynchronized

### ISSUE THREAD

**Issue by iangabrielsanchez** [nocodb/nocodb#3587]
```
NocoDB used as docker : true
NocoDB version : 0.92.4
Database used in NC_DB URL  : pg
Project was created  by clicking : New Project
Database on which spreadsheet is created : pg
OS on which NocoDB is running : ubuntu
Node.js version if running as node : 
Database version : 13.4
```

**Steps To Reproduce**

1. Deploy nocodb on ecs with at least 2 instances and connected to a single db
2. Configure a load balancer to connect to these instances
3. Create a project and some tables using the nocodb API
4. If you look at the GUI per host, you will see that the tables they show will become inconsistent and would require manually calling the sync metadata endpoint

Is there a way to make sure that these instances are always synchronized?

**Comment by pranavxc** [comment]
You have to use a shared Redis cache or need to disable the cache. Cache disabling is not recommended since it will slow down the application.

Set [`NC_REDIS_URL`](https://docs.nocodb.com/getting-started/installation#environment-variables) environment variable to provide Redis instance access.

**Comment by pranavxc** [comment]
Assuming both instances are using the same `NC_DB` URL. In that case, you have to use a shared Redis cache or need to disable the cache. Cache disabling is not recommended since it will slow down the application.

Set [NC_REDIS_URL](https://docs.nocodb.com/getting-started/installation#environment-variables) environment variable to provide Redis instance access.

**Comment by o1lab** [comment]
Would need the use of redis as mentioned above.
