### ISSUE TITLE
DB_QUERY_LIMIT_DEFAULT seems to not be working anymore

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#3617]
In version 0.96.4 DB_QUERY_LIMIT_DEFAULT seems to not be working anymore. I have set mine to 100, and from this version I only have 25 rows per page.

Details here : https://github.com/nocodb/nocodb/discussions/942#discussioncomment-3639304

**Comment by wingkwong** [comment]
@occamssafetyrazor Use `200` instead of `'200'`. By doing so, you should only get `100`.

<img width="935" alt="image" src="https://user-images.githubusercontent.com/35857179/195320166-bb592f9e-74f9-4aef-b039-b2eaa1c957e8.png">

The default limit is calculated as ``max(min(DB_QUERY_LIMIT_DEFAULT , DB_QUERY_LIMIT_MAX), DB_QUERY_LIMIT_MIN)``. By default the initial values for ``DB_QUERY_LIMIT_DEFAULT``, ``DB_QUERY_LIMIT_MAX``, and ``DB_QUERY_LIMIT_MIN`` are ``25``, ``100``, and ``1`` respectively. 

If you just set `DB_QUERY_LIMIT_DEFAULT` to `200`, then it would become 

```
max(min(DB_QUERY_LIMIT_DEFAULT , DB_QUERY_LIMIT_MAX), DB_QUERY_LIMIT_MIN)
= max(min(200 , 100), 1) 
= 100
```

Therefore, if your target ``DB_QUERY_LIMIT_DEFAULT`` exceeds the default value of  DB_QUERY_LIMIT_MAX which is ``100``, then you need to increase ``DB_QUERY_LIMIT_MAX`` as well. 

Conclusion:

1. set `DB_QUERY_LIMIT_DEFAULT` to `200` instead of `'200'`
2. set DB_QUERY_LIMIT_MAX to a value which is greater than your new `DB_QUERY_LIMIT_DEFAULT`

Free feel to ping us in discord if you have further questions. Thanks.
