### ISSUE TITLE
After upgrading version attachment not found

### ISSUE THREAD

**Issue by whyteserious** [nocodb/nocodb#3779]
```
Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **mysql2**
OldPackageVersion: **0.92.4**
NewPackageVersion: **0.96.4**
```

**Steps To Reproduce**
Replace Mirror File 
attachment not found

**Expected Behavior**
Database location where attachments are stored
fix the problem

**Comment by o1lab** [comment]
You would have to mount the file as shown in the docs or install s3 (cloud storage) credentials.

**Comment by wingkwong** [comment]
@whyteserious 

> what do you mean "mount the file as shown in the docs"？

You may refer to [here](https://docs.nocodb.com/getting-started/installation#docker). By mounting, it means the uploaded files will be stored in the given mount filesystem instead of the container.

> attachments don't push in the database？

Attachments are not stored in the database. 

> Click the attachement，it's display not found

If you haven't mounted your container nor configured any storage plugin, that means your uploaded files will be stored inside the container (`/usr/app/data/`). When you upgrade, the container will be destroyed and will be recreated. Therefore, your files will be gone and you are expected to see file not found.
