### ISSUE TITLE
TINYINT(1) values un-settable via form view

### ISSUE THREAD

**Issue by dayreiner** [nocodb/nocodb#3789]
NocoDB used as docker : true
NocoDB version : 0.96
Database used in NC_DB URL  : mysql
Project was created  by clicking : New Project by connecting to external database
Database on which spreadsheet is created : mysql 
OS on which NocoDB is running : Amazon Linux 2
Node.js version if running as node : 
Database version : MariaDB 10

**Steps To Reproduce**

- Add a TINYINT(1) column to a table with a default value of 1 or 0 and import in to project
- In table view, the column is represented with checkboxes which can be clicked to flip the value from 0 to 1. Working as expected.
- In form view, the field name is shown with the checkbox icon beside it and an empty, non-clickable text box. There is no way to toggle the field on the form, so if it is a required field the form cannot be submitted. 

**Expected Behavior**

I would expect the behaviour to be the same between column and form views. Form should show a clickable checkbox to set the 0/1 (Y/N) value just like table view does.

Field as it appears in table view:

![image](https://user-images.githubusercontent.com/5184541/191993052-815272ee-7a74-430e-ab18-959755de9a91.png)

Field as it appears on form view (text box is not editable):

![image](https://user-images.githubusercontent.com/5184541/191992772-168bd2e3-ce56-4920-9ae4-9818ee181205.png)

**Comment by wingkwong** [comment]
@dayreiner It looks like same as https://github.com/nocodb/nocodb/issues/3613. The problem was the checkbox located in the leftmost area of the input which made users hard to click. You may try in v0.97.0 which you can click everywhere in the input to check / uncheck.

Here's a demo I tried in 0.97.0.

[screen-recorder-sat-sep-24-2022-11-30-35.webm](https://user-images.githubusercontent.com/35857179/192078281-06bd4ce8-ffa8-47b4-91f0-71faf2ea3636.webm)

**Comment by dayreiner** [comment]
Confirming in 0.97 the form field shows the checkbox when you hover over the field and can select it. Looks good!

**Comment by o1lab** [comment]
Good to close. Thanks for confirming.
