### ISSUE TITLE
🐛 Enhancement: Count of a 100 Million table without a PK takes a lot of time

### ISSUE THREAD

**Issue by o1lab** [nocodb/nocodb#4287]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- Count of a 100 Million table without a PK takes a lot of time
- This makes it really slow to show the grid view of the table.
- From `drasticstuff` on discord.

### Desired Behavior

.

### Project Details

- Latest

**Comment by o1lab** [comment]
If the count takes a lot of time - we fallback to pagination which allows users to go the next page and does not show the total row count,

**Comment by m-thomson** [comment]
Hi @o1lab how is this supposed to work exactly? I've got a lot of records and just seeing a sample of my data takes about ~30s. Is it possible to disable the `count(*)` completely? None of the other tools I've been evaluating bother printing the total (probably because it's such an expensive operation).

![Screencap2024 05 29 1835](https://github.com/nocodb/nocodb/assets/5273016/e6e14381-eca3-4100-a459-b6cd9dbc6286)

**Comment by m-thomson** [comment]
>If the count takes a lot of time - we fallback to pagination which allows users to go the next page and does not show the total row count,

Hi @o1lab can you elaborate on what should be happening here? What is the threshold for "takes a lot of time" ? Thanks.
