### ISSUE TITLE
🐛 Bug: Persian forms are loaded from Left to Right

### ISSUE THREAD

**Issue by okaeiz** [nocodb/nocodb#4388]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Change the interface language into Persian.
2. Create a table with Persian columntypes and records
3. Create a form.
4. Share the form.
5. See? The whole form is Persian but it's LTR (Screenshots included).

### Desired Behavior

I need to have a fully localized interface, with Persian language and RTL elements. 

### Project Details

Node: **v16.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **mysql2**
ProjectOnRootDB: **false**
RootDB: **mysql2**
PackageVersion: **0.98.4**

### Attachements

![Screenshot (15)](https://user-images.githubusercontent.com/100111649/201646733-46112287-a2c4-4589-830c-dd8d841e7f37.png)

**Comment by bcakmakoglu** [comment]
Thanks for reporting.
Relevant fix is ready in [this PR](https://github.com/nocodb/nocodb/pull/4390).

**Comment by okaeiz** [comment]
We checked the PR docker image and it worked fine in windows but when we open the form in mobile phones, it is still LTR.

**Comment by bcakmakoglu** [comment]
Mh... I see.
The problem here is that when you use your mobile device, the language settings aren't detected , while on windows you'll have some language settings stored by NocoDB. 
Technically we won't be detecting such settings if you share the link with a user that has no access to your nocodb, so it would always fall back to LTR settings.

That's of course not gonna work, I can't guess what language you're going to use in your form either.
The language settings are saved *per user* not *per project*, so guessing from there won't work either.

What we could do is add an option to force LTR/RTL direction, like another checkbox that would cover this for now.
Otherwise I can at best guess what direction to use from the browser settings of a user, but if the browser is running an LTR language and you use an RTL language on your forms, it would still use the wrong direction.

@okaeiz Are you okay with an additional option to choose the direction?

We could of course allow to select the actual language but seeing as we don't translate anything in the forms there wouldn't be much use in selecting the language.

**Comment by okaeiz** [comment]
Thanks for your clear explanation.
The idea of checking the browser settings is not going to work. Because most of us keep the phone's default language (mostly English).
Therefore, I agree with the other solution you just mentioned. It's great to be able to choose the direction.

**Comment by o1lab** [comment]
Instead of a checkbox, we can do this. 

If the language is RTL - while creating the shared form view URL. 

We can prefix a query param. `?i18n=RTL` and based on which we can handle.

**Comment by okaeiz** [comment]
This is fine, too.
So before publishing the form, NocoDB can recognize its direction.

**Comment by bcakmakoglu** [comment]
@o1lab that is too arbitrary to be honest, because the language is not set per project but by each individual users *browser* (the language is stored in local storage).
So if I use the same form you do and i happen to use Danish, my links are Danish, yours are whatever language you picked.

That is kind of random to me 😅

**Comment by bcakmakoglu** [comment]
Also, what if I use an English UI but I want my form to be in Farsi? Now my form would still have the wrong orientation or I would need to switch my UI language each time I generate a link just so it has to correct orientation.

Auto-detecting the direction is really more trouble than it's worth imo.

**Comment by okaeiz** [comment]
Have you tried any solution? This is kind of emergency for me :)

**Comment by okaeiz** [comment]
https://github.com/nocodb/nocodb/commit/f365c1ef948037a47766491ebc4caafcb1188b4a#comments

I deployed this PR image and it is working fine but when I click on the checkbox, the check symbol doesn't appear.

**Comment by bcakmakoglu** [comment]
@okaeiz there was a typo, should be fine with the latest commit
