### ISSUE TITLE
🔦 Feature: Change Kanban Stack Order

### ISSUE THREAD

**Issue by 3699n** [nocodb/nocodb#4487]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Currently, the Stacks on a Kanban board seem to always be sorted alphabetically, even when a different order is selected for the Single Select type in the Grid view. In order to make a Kanban meaningful, it is important that the stacks are ordered correct (eg. that TODO is before DONE). 

### Suggested Solution

By default, a Kanban should copy the ordering of the Single Select type on which it relies. Additionally, when pressing "Add/Edit Stack", one should be able to rearrange the entries.

**Comment by wingkwong** [comment]
Can you provide your project info? I just tested a bit in latest version and have the following findings.

1. By default, the kanban stack does follow the order of the single select options. E.g. I created 3 options `3`, `2` and `1` and the stack order goes `3`, `2` and `1` rather than `1`, `2` and `3`.
2. Once you've created a kanban view, you can drag the whole stack to the position you want. The stack order will be saved as well and it won't affect the original order of the single select options given that it is exclusive to the current view.

**Comment by 3699n** [comment]
1. was not the case for me
2. Works for me but I was unaware that this was an option. Maybe it makes sense to make this option more clear in the UI?

**Comment by wingkwong** [comment]
Please share your project info. If possible, please provide a video as well.

**Comment by dstala** [comment]
@3699n Closing this thread. If issue still persists on latest release, please reopen.
