### ISSUE TITLE
🐛 Bug: formula value in webhook comes up as output

### ISSUE THREAD

**Issue by matan1905** [nocodb/nocodb#4756]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

create a new table with a formula column.
I used the simple formula "NOW()" but it seems like all formulas behave the same.

next, create a webhook after update:
<img width="689" alt="image" src="https://user-images.githubusercontent.com/24731932/210665865-919a1169-e7b4-4c5f-ac65-254395801635.png">
When testing the webhook and when using it, the formula field is "output":
<img width="635" alt="image" src="https://user-images.githubusercontent.com/24731932/210665996-ba5ffcd7-4fa3-4cee-841b-e6f27a5de906.png">

### Desired Behavior

I would expect the formula to be the resulting calculation - the value of NOW()

### Project Details

Node: **v16.17.1**
Arch: **arm64**
Platform: **linux**
Docker: **true**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.100.2**

**Comment by wingkwong** [comment]
It's working fine on my local with the same setup. `output` is supposed to be shown in sample payload for the showcase and I don't see it is being used in the actual hook. 

Can you double confirm that the result you saw was actually fired by the actual webhook instead of the testing one?

**Test Webhook**

When you click `Test Webhook`, it will be using sample payload so `output` is expected.

![image](https://user-images.githubusercontent.com/35857179/210987086-5d426cc0-72ba-4c27-b29d-36ef72c7d771.png)

**Actual Hook**

When you trigger the webhook by updating data, you should see the actual data instead of sample data.

![image](https://user-images.githubusercontent.com/35857179/210981207-e8afa3a7-cbc8-4a17-aadc-91afe3b7ad92.png)
![image](https://user-images.githubusercontent.com/35857179/210981403-8d9aeaa7-f870-4c7b-9f3d-8f52f9948d1a.png)

![image](https://user-images.githubusercontent.com/35857179/210982786-b3ae4b41-62b4-4994-9edc-ee252077a322.png)
![image](https://user-images.githubusercontent.com/35857179/210982725-6e7bd67d-9f37-4b12-a6d4-5189bfb1f486.png)

**Comment by matan1905** [comment]
It works! my bad, sorry!
