### ISSUE TITLE
🔦 Feature: LinkToAnotherRecord with filtered data

### ISSUE THREAD

**Issue by sepbin** [nocodb/nocodb#4899]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

**UPD by wingkwong: See [this comment](https://github.com/nocodb/nocodb/issues/4899#issuecomment-1404534857) for English description.** 

![image](https://user-images.githubusercontent.com/3182421/213882910-692902b6-aa00-4324-a606-c33fe06a3ca1.png)
如果不能选 视图 ， 我无法在统计时，对结果加入筛选。。

如果能加入视图关联， 这将是一个完美无缺的软件。。超越所有同类软件，加油

### Suggested Solution

建议加入， 可选择 已选表的视图

**Comment by wingkwong** [comment]
@sepbin Please write in English.

**Comment by sepbin** [comment]
but i can't english. im chinese

**Comment by wingkwong** [comment]
@sepbin 为什么你要需要选择视图？ 视图是指这些吗？

![image](https://user-images.githubusercontent.com/35857179/213994852-0c23e5f3-2950-4d04-a154-4649c670c4bd.png)

**Comment by sepbin** [comment]
> 

是的。是指这个。因为视图能增加条件。比如 员工 <> 工作内容， 这样的表。某些时候，我只希望关联 状态为 【已完成】的工作内容，那么，该工具没有提供筛选函数或其他功能。。 如果可以关联视图，那么我可以在视图设置好条件，这是不是能解决很多问题。。。如果你还想做一个 该员工 本月已完成工作内容统计，可以关联视图，就非常容易完成，这是很实用的。

**Comment by sepbin** [comment]
@wingkwong 
当您的软件实现功能，我能例举一些实用场景
1，我不用每次去输入 完成时间， 我只需要筛选出 状态为【通过】的 内审记录，然后  rollup记录时间 就能自动为我填写【内审完成时间】
![image](https://user-images.githubusercontent.com/3182421/214106012-cd194a95-f2fd-4020-8b35-02a2c88fd3e9.png)
2，这里的【需求总数】我并不想统计状态为【已完成】
![image](https://user-images.githubusercontent.com/3182421/214106581-02075e6d-d631-4b57-b044-c92733eeedcd.png)

当然，还有很多场景。。如果能够实现它，真的很酷~

**Comment by wingkwong** [comment]
@sepbin 如果你创建了一个表，所有视图的数据都是一样的。视图只是怎去表达数据而已。LinkToAnotherRecord只是连将两个表进行关联。

例如现在有两个表，一个是员工，一个是工作内容。员工可以有多一个工作，所有有HasMany的关联。现在员工A有两个工作，在现在的版本，在员工表上，A就会有工作A跟工作B。你现在希望是，你可以有一个方法去筛选，如果工作B是状态为 【已完成】，那在员工表上员工A只有工作B，而不是工作A跟工作B，对吗？

**Comment by sepbin** [comment]
@wingkwong 对的，大佬。希望能有一种方法实现这种关联的筛选功能。。或者增加某种函数去实现。但我建议您用目前的视图功能去实现，目前视图本来就可以储存筛选条件。对于用户体验而言，这非常直观，我只需要储存好视图的筛选条件，然后关联这个视图，就完成了，这比用其他方式对于用户简单直观得多

**Comment by sepbin** [comment]
![image](https://user-images.githubusercontent.com/3182421/214380500-b023dfc5-6b49-40ef-b9ab-97351189c224.png)
建议的操作步骤如图所示。当然我觉得可能这种做法有难度，但仍希望大佬们可以做出这么炫酷的功能~

**Comment by wingkwong** [comment]
好的，我大概明白你的需求。你可以說一下你怎樣通过API去实现吗？我會更改一下這個PR的標題和翻譯一下。

**Comment by wingkwong** [comment]
## English Translation:

This PR is to request LTAR columns with filtered data. For example, let's say there are two tables - `employees` and `tasks`. The table `employees` has a `HasMany` column to `tasks`. 

Table `employees`
![image](https://user-images.githubusercontent.com/35857179/214754330-372b6d69-3d6d-4398-8347-20ec3e5cfc93.png)

Table `tasks`
![image](https://user-images.githubusercontent.com/35857179/214754344-05410c9d-9d88-410b-93ae-b2210ffac94b.png)

What sepbin wants is to show those tasks in table `employees` with some conditions (says `status = done` in table `tasks`). In this case, since `task a` and `task b` are marked as done, they won't be shown in table `employees`. The expected result would be showing `task c` for `employee a` in table `employee` only (since the condition `status = done`  is false). 

What he proposes is to select a view when creating a LTAR column. In above example, the view will be with the filter `status = done` in table `tasks`.

**Comment by sepbin** [comment]
@wingkwong 
![image](https://user-images.githubusercontent.com/3182421/214917162-b1ed4495-a4a4-44e9-8bcc-5798e1e2b58b.png)

Such a function is needed, and many people should need it

**Comment by frogsinging** [comment]
that's good, I also especially need this function,Do you have a plan?

**Comment by OdinZhang** [comment]
cannot wait for this feature. really need this feature

**Comment by dstala** [comment]
Feature is now supported as on 251.2
