### ISSUE TITLE
Feature request : personnalization of title and logo

### ISSUE THREAD

**Issue by flavienbwk** [nocodb/nocodb#494]
Hi,

Currently, I don't see where I can edit the name and logo top left of NocoDB.

The NocoDB brand is already cited top right, I think it might be a good move to give the option to your users personnalizing their instance title and logo.

Is it already possible ?

Thanks,

**Comment by candideu** [comment]
I second this! In the share view for the Forms, the logo appears twice, and the bigger, middle one makes it seem like it's a Noco form instead of our own. That area should be used for the user's logo or for an image, much like Airtable and Google Forms do:

![image](https://user-images.githubusercontent.com/55474996/142492509-70692b7a-b815-4d40-b0ea-069dbb2573af.png)

**Comment by jonwsoto** [comment]
Any update on this customization?

**Comment by almereyda** [comment]
Interestingly this branding is also not visible when previewing a form, or while editing it, and comes to a surprise when opening the private link to it.

**Comment by prononext** [comment]
Any update on Customization would be really nice 🥇

**Comment by 0x7466** [comment]
+1

**Comment by solferi** [comment]
+1 to this.. I manage two nocodb servers at the same time. It helps when there's a distinction of the two servers through title/branding.

**Comment by dstala** [comment]
Customisation of the banner & logo is now available as an enterprise feature.

**Comment by dunavista** [comment]
right........so this not open source then

**Comment by 0x7466** [comment]
@dunavista Open source doesn't mean you have the right to demand features. If you want that, fork it and implement it yourself.
