### ISSUE TITLE
Feature : New columns => created_by, last_updated_by 

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#499]
Store whoever created / last updated the data in ROW level. 

**Expected behavior**

When``User A`` creates a new row
-  ``created_by`` will be automatically filled as ``User A``.
- ``last_updated_by`` will be automatically filled as ``User A``

When``User B`` updates an existing row
- ``last_updated_by`` will be automatically changed to ``User B``.

Node: v12.22.1
Arch: x64
Platform: linux
Docker: true
Database: pg
ProjectOnRootDB: false
RootDB: pg
PackageVersion: 0.11.23

**Comment by wingkwong** [comment]
It's not that efficient to check who created / modified the record last one by one. Isn't it a bit weird then u can show created_at and updated_at as system fields in the grid but not created_by and updated_by? Even they are not meant to be system fields, can we have a function to get the current user? Audit is a good feature to track all the changes, but I think that s not the case.

**Comment by o1lab** [comment]
created_at and udpated_at are simple columns within a table.

created_by and updated_by have to be referenced from another table (or even database since user is in meta db) - so there is large overhead to get the 'primary value' using belongs to relation in spreadsheet view.

**Comment by yorkshirelandscape** [comment]
I'd like to second this request. I realize it's not quick or simple, but it's important. Being able to see who created or updated a record at a glance is something I wish nocodb had every time I create a new table.

**Comment by zsmith009** [comment]
Just letting you know this is a deal-breaker for me for now & a basic feature available in other cloud DB such as airtable, which I was looking to replace. 

The ability to have a cell indicating last_updated is necessary for my use case. I will be dropping nocodb for now.

**Comment by dstala** [comment]
supported in v0.204.0

**Comment by aleBranching** [comment]
Hello, love this project. The created by still has considerable limitations when connecting to an external database. 
I create another "base" such that a user can only view relevant forms because I need them to be a creator but not access other tables. However when they create a record the created by on a different base with the same database connection does not update. 

Current possible workarounds is on data insert webhook that then updates the record

**Comment by salim-b** [comment]
> The created by still has considerable limitations when connecting to an external database.

@aleBranching I've filed a feature request to support updating `created_at/by` columns in external DBs that weren't created via NocoDB, see https://github.com/nocodb/nocodb/issues/7796.

**Comment by aleBranching** [comment]
Would it work if the database was created like this?

```
docker run -d --name nocodb-postgres \
-v "$(pwd)"/nocodb:/usr/app/data/ \
-p 8080:8080 \
-e NC_DB="pg://host.docker.internal:5432?u=root&p=password&d=d1" \
-e NC_AUTH_JWT_SECRET="569a1821-0a93-45e8-87ab-eb857f20a010" \
nocodb/nocodb:latest
```

**Comment by salim-b** [comment]
@aleBranching Filling the `created_by` and `updated_by` columns with the NocoDB user ID works as long as the columns have been created via NocoDB, also in tables from external data sources including PostgreSQL. All tables created via NocoDB have these columns by default (but they are hidden from the UI by default).

**Comment by salim-b** [comment]
> The manager has a base with all the data. The worker base only has a form via nocodb (...)

I can't really follow, I suppose. How did you set that up? Your "worker base" has a form view for a table in *another* "manager base"? 🤨

**Comment by aleBranching** [comment]
This an overview of what I have. There's 2 bases one for manager, another one for worker. They are using the same postgresql connection. The reason for doing this is because I want to have different "user groups" with different permisions and different data tables. that they can view/edit. As you can see there is a `create` column that is not properly updating. It is updating however if I write the data in the same base, eg. in the main/manager base I add a data entry the column populates. However whenever the worker completes the form the Main base column does not update. 
![image](https://github.com/user-attachments/assets/18cc416a-4229-41b4-98de-6ed0183270fd)

This is what the worker can see:

![image](https://github.com/user-attachments/assets/b629b487-05d4-437e-ad47-d9a5c20ec921)


This is their permisions: 
![image](https://github.com/user-attachments/assets/317b114c-6679-48f4-b958-0d9bcf9ee5ad)


Hope that clears up what I mean. It seems Like I would need to create a frontend with a small backend that will populate a custom column. This product removes a lot of "boilerplate" of editing, viewing data, but for creation I would need a custom frontend, with a Users table in postgresql, However that adds a bit of inconsistency as there would be a User table in postgresql as well as nocoDB metadata table.

**Comment by salim-b** [comment]
> They are using the same postgresql connection.

Ah, now I understand, thanks for clearing that up.

It appears to me you discovered yet another limitation (or bug, I can't really tell what's the expected behaviour here) of NocoDB's `created_by` and `updated_by` auto-fill, then. I [mentioned it](https://github.com/nocodb/nocodb/issues/7796#issuecomment-2324728463) in the other issue.

**Comment by aleBranching** [comment]
Thanks!
