### ISSUE TITLE
🔦 Feature: API - Delete Attachment

### ISSUE THREAD

**Issue by IsserTerrus** [nocodb/nocodb#5152]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

In API we can't delete an Attachment

### Suggested Solution

Add a DELETE API for Storage with URI in parameter

**Comment by mertmit** [comment]
We are currently developing an attachment clean-up feature that will prevent orphan attachments from persisting in storage. The deletion of files will be automatically managed when all associated references are removed. This is because NocoDB reuses attachments during copy and duplicate operations.

While a direct delete API will not be provided, this solution should address the underlying issue. So I will close this issue.
