### ISSUE TITLE
Map View Follow-up items

### ISSUE THREAD

**Issue by wingkwong** [nocodb/nocodb#5203]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- [ ] In Expanded Form, the style is not aligned after setting a value.
![image](https://user-images.githubusercontent.com/35857179/221085653-cb984644-9367-44d6-99bd-4065f9b56b73.png)
![image](https://user-images.githubusercontent.com/35857179/221085689-45e47079-4f37-4a83-9f99-a6c6ab499c46.png)

- [ ] share view is not working if you copy the link to another browser. To give you more context, for share view we are using public api instead of the original one, which doesn't require authentication. Please refer the implementation in other views.

- [ ] shouldn't allow all types (check under `packages/nocodb-sdk/src/lib/sqlUi`)
![image](https://user-images.githubusercontent.com/35857179/221087713-6f7fad5c-4d28-4295-b2fd-0675226160aa.png)

cc: @spaudanjo @flisowna 

### Project Details

Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
RootDB: **mysql2**
PackageVersion: **0.105.3**

**Comment by spaudanjo** [comment]
- [ ] In Shared View, currently it's not loading/showing more than 25 data points (might be related to above's `share view is not working if you copy the link to another browser. To give you more context, for share view we are using public api instead of the original one, which doesn't require authentication. Please refer the implementation in other views`)

**Comment by spaudanjo** [comment]
- [ ] Not possible to see markers details in shared view (since shared view doesn't open the expanded view)
