### ISSUE TITLE
🐛 Bug: Replace in formula issues

### ISSUE THREAD

**Issue by telecentru** [nocodb/nocodb#5209]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

I try to create a formula so that the quotes (") from a text are replaced with nothing: (REPLACE({title}, """, ""))
I tried to escape the " character like this: (REPLACE({title}, "\"", ""))
I tried to escape the " character like this: (REPLACE({title}, """", ""))
I tried to escape the " character like this: (REPLACE({title}, '"', ''))

### Desired Behavior

It doesn't work. Is there a solution to this, or is this bug?

### Project Details

It doesn't work. Is there a solution to this, or is this bug?

**Comment by kimmel-** [comment]
Hello, just tried to replace: REPLACE({CustomAttributes}, "\"attribute_code\":\", "")
With a great fail on char 53
Basically trying to clean up stuff from fields. 

While: REPLACE({CustomAttributes}, "attribute_code", "") works fine

If I try to clean what I'm willing to clean: \"attribute_code\":\ nocodb is not able to handle it seems.
Since seems to be related to this issue, I'm adding the comment here.

I'm currently using last nocodb version as of today, via elestio

**Comment by kimmel-** [comment]
@wingkwong in case you want to revisit this issue or open a new one

**Comment by wingkwong** [comment]
@kimmel- please create a new issue.
