### ISSUE TITLE
🐛 Bug: For Sqlite DBs, cannot send Forms when a column contains a '?'

### ISSUE THREAD

**Issue by spaudanjo** [nocodb/nocodb#5415]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

* With a NocoDB project based on Sqlite
* Create a table and add a column that contains a '?', e.g. 'Does this person need medical support?'
* Create a form for that table, including that column
* Try to send the Form
* It gives you an error that says `The column nc_mahf___Sheet does not exist.`

When removing the question mark from the column name, the sending works. 

### Desired Behavior

It should be possible to send Forms for any columns, regardless of their name. If question marks or other special characters are not allowed/supported as columns titles, it shouldn't be possible to set them in the UI. 

### Project Details

Database: sqlite
Docker: false
NocoDB version: current develop (as of 2023-04-03)
OS: MacOS

**Comment by marlon0** [comment]
This also produces an error when trying to create new records through the Table UI

**Comment by frankMagoba** [comment]
Hi @o1lab can I pick this up?

**Comment by frankMagoba** [comment]
@o1lab is this still up?

**Comment by o1lab** [comment]
This will be a tricky one. I understand you'd other issues assigned in your name. Do you please take up issues that are easy to get to.

**Comment by kurijn** [comment]
I just had to find out this issue as well. As it's not evident to find out the error is due to the question mark, I think many people may be bumping onto it not knowing what the cause is. If the resolution is tricky, perhaps it would help already to apply a temporary workaround such as a providing a clearer error message, stating there is a question mark (or other special character?) which unfortunately is not yet supported.

**Comment by dstala** [comment]
works as of v0.202.5; @spaudanjo reopen this thread if issue still persists

**Comment by spaudanjo** [comment]
Thanks, will do! :)
