### ISSUE TITLE
[Feature] Image column type (in order to display images in each rows)

### ISSUE THREAD

**Issue by MatteoGauthier** [nocodb/nocodb#5571]

**Comment by wingkwong** [comment]
Can you elaborate more? What's the difference between this and attachment type?

**Comment by MatteoGauthier** [comment]
Sorry for the lack of detail 😅. I have a DB with an `field` that contains urls and I wanted to preview those image URLs directly in the Table View. The attachment type only allows binary files and images are generally stored as URL (from S3).

**Comment by wingkwong** [comment]
Are you proposing a new column type or a new feature on top of URL column type (if it is an image)?

**Comment by MatteoGauthier** [comment]
> Are you proposing a new column type or a new feature on top of URL column type (if it is an image)?

Two possibilities :
- I think it would be nice to allow URLs in the `Attachments` field
- An option in the URL column properties like this ⬇️ ("URL is an image ?")
![image](https://user-images.githubusercontent.com/32040951/236139824-ba396373-fdba-4401-b500-4266c7088f9a.png)

**Comment by wingkwong** [comment]
- Import via URL would be available in the future. We planned that before.
- For an option in URL, the URL can be purely links. I remember that there is another open issue requesting a feature like if the link can be previewed, then show the preview result. Therefore, instead of showing `URL is an image`, `Show Preview` may be more a suitable text.

**Comment by dstala** [comment]
https://github.com/nocodb/nocodb/issues/1434
