### ISSUE TITLE
🐛 Bug: Currency datatype, cell with value 0 displayed as empty cell

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#5607]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

<img width="414" alt="Screenshot 2023-05-07 at 7 18 23 AM" src="https://user-images.githubusercontent.com/86527202/236653866-d8f8da2a-40c2-4ace-bda7-98a30cd325ca.png">

create currency field; add some entires as 0; refresh
column to the right is formula field displaying actual values held in cell

### Desired Behavior

display 0 along with associated prefix chosen by end user

### Project Details

issue reported by discord user; he had claimed all single digit cells were not displayed. could reproduce it only for 0 valued cells.

Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.107.0-beta.0**

**Comment by peterlang-p** [comment]
Hey everyone,

It looks like this issue was originally fixed two years ago. However, I'm encountering the exact same problem in version 0.262.5.

I've attached a screenshot for reference:
![Image](https://github.com/user-attachments/assets/e004d0e9-4b49-4225-a83a-d675db0ea55a)

Has anyone else experienced this recently? Any suggestions on how to resolve it?

Thanks!
