### ISSUE TITLE
🐛 Bug: (Swagger UI) Unable to render this definition

### ISSUE THREAD

**Issue by hialvaro** [nocodb/nocodb#5804]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Visit the Swagger API docs for a project from `APIs & Support` Help Center
2. See the error:

![](https://i.imgur.com/YGlrZlT.png)

### Desired Behavior

Have a functioning API Docs.

### Project Details

Node: **v16.19.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **sqlite3**
PackageVersion: **0.108.1**

**Comment by pranavxc** [comment]
It expects an access token in your browser localstorage since `swagger.json` endpoint is not public now. 

To access the page do the following steps

1. Open your dashboard URL and login with your credential
2. Now you can access the Swagger UI enpoint

If still facing the issue check your browser network tab and share the `swagger.json` endpoint response details.

**Comment by dstala** [comment]
https://github.com/nocodb/nocodb/issues/5804#issuecomment-1578750458
