### ISSUE TITLE
🐛 Bug: SDK for attachment type not working in node environment

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#6062]
### Project Details

Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
RootDB: **mysql2**
PackageVersion: **0.109.4**

**Comment by j-stahl** [comment]
Same issue on 0.109.5.
In nocodb-sdk version 0.96.4 the SDK is using File() objects. So my code could upload files properly.
```
return this.nocoDbApi.storage.upload({path: path}, {files: [_file], json: json})
      .then((result) => {
...
```
This was fine because storage.upload was expecting this:
```
    storage: {
        /**
         * No description
         *
         * @tags Storage
         * @name Upload
         * @summary Attachment
         * @request POST:/api/v1/db/storage/upload
         */
        upload: (query: {
            path: string;
        }, data: {
            files?: any;  // <<<<<<< SEE HERE <<<<<<<<
            json?: string;
        }, params?: RequestParams) => Promise<any>;
```
The new code expects something like AttachmentRequest() objects. Not even an Attachment() object, which would make quiet more sense, than just a request of an attachment.
I guess the SDK is automatically generated and so this bug has sneaked in.

**Comment by sheldon-welinga** [comment]
@o1lab is this issue available?

**Comment by dstala** [comment]
@sheldon-welinga if you are able to reproduce this issue, you can pick this up

**Comment by sheldon-welinga** [comment]
Ok sure, yea I think I saw the cause of the bug. JS ecosystem can bypass it however TS ecosystem will be caught up
