### ISSUE TITLE
line height cannot be set, and content cannot be wrapped

### ISSUE THREAD

**Issue by binli123-max** [nocodb/nocodb#6183]
Hello, the line height cannot be set, and the content cannot be wrapped, and some lines cannot be hidden, and there is no group display

**Comment by wingkwong** [comment]
Please show your project info and a video / some screenshots to demonstrate the issue.

**Comment by binli123-max** [comment]
您好，我是李斌！您的邮件，已收到！

**Comment by binli123-max** [comment]
The First---  the content cannot be wrapped
![image](https://github.com/nocodb/nocodb/assets/110003071/5e7501a7-71ee-4b27-bcec-d406217c8c1a)
The second---the line height cannot be set  custom height
![image](https://github.com/nocodb/nocodb/assets/110003071/7462f7fe-2380-447a-8ebd-f9040fc236de)
The Third---it  cannot  grouped  by  one field ,   just   Kanban  By  singleselect

**Comment by binli123-max** [comment]
![image](https://github.com/nocodb/nocodb/assets/110003071/ec797ea4-4182-4efd-94d0-cd3f060c1e90)

**Comment by wingkwong** [comment]
1. It's by design. Wrapping the long content would cause a bad UX. 
2. Custom row height is not available. You can only set the global row height.
![image](https://github.com/nocodb/nocodb/assets/35857179/b73e730e-dd3b-4e49-a897-2ef31f7745f9)
3. I assume you are talking about Group By in Grid View. If so, please wait for the future release.

**Comment by binli123-max** [comment]
Thank  you   for  your  fast  answer ，your project is very  good ，Thanks  your   help
