### ISSUE TITLE
🐛 Bug: 'subdirectory_arrow_right' text appears before column names

### ISSUE THREAD

**Issue by PhilDu77** [nocodb/nocodb#6446]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

open a table with foreign key to others tables. ( tables with link 'has many' to the main table)
for all column with a foreign key to an other table the name of the column begin with 'subdirectory_arrow_right'
ex: for the column origine the name is:' subdirectory_arrow_right origine'

there is a similar other strange text when I pass the cursor at the right side of the Nocodb logo( position of the hide side bar function): 
'Keyboard_double_arrow_left' text

### Desired Behavior

Only show the normal name of the column: origine

### Project Details

NoCoDB version 0.111.4
linux debian
no Docker installation
database MariaDB
![subdirectory_arrow_right' text ](https://github.com/nocodb/nocodb/assets/141258984/699cd689-399b-4de4-9f2b-2be5f6e3c7b7)
![Keyboard_double_arrow_left text](https://github.com/nocodb/nocodb/assets/141258984/9389c268-1128-4f06-a29e-3bbfe0e04440)

**Comment by dstala** [comment]
@PhilDu77 Does this persist forever? or appears only when you load for the first time?

**Comment by PhilDu77** [comment]
yes this persists forever
this is not only for columns linked to other table(subdirectory_arrow_righr origine *) but also for individual fields (here text_fields Nom*)  and for tables linked to the table(here table_rows Tdata)


This problem appears with the Mozilla Firefox browser but not at all with Google Chrome !

**Comment by PhilDu77** [comment]
there is not ploblem with the Opera browser too.
finaly with FIreFox the text: 'subdirectory_arrow_right' appears before all names in noCoDB.
a lot of people use FireFox that is a problem to be able to use NocoDb.

**Comment by dstala** [comment]
@PhilDu77 I tried on Firefox 119.0.1 (64-bit) & it seemed to work fine. I am on iOS. Can you try again on latest firefox to help us narrow down if this issue is specific to Linux ENV?

**Comment by PhilDu77** [comment]
On my PC the version is also Firefox 119.0.1 (64-bit) but under windows 10 enteprise. NocoDb is instaled under linux debian.
I tried to mention this issue to Mozzila but they can't reproduce the phenomenon without a NocoDb real acces.

Thanks to considerate my ask. actually temporarily i use Opera browser but the broswer installed in my company is Firefox.

**Comment by PhilDu77** [comment]
you can see also this phenomenon on my srceen shoot in the Bug: #6208

**Comment by PhilDu77** [comment]
Have had to update my windows10 version to 21H2 for a other reason.
Since the problem disappeared.
thanks to watch this issue!

there is still the Bug: https://github.com/nocodb/nocodb/issues/6208 ...

**Comment by dstala** [comment]
Closing this issue as it's marked as fixed after upgrade by @PhilDu77

**Comment by sqkkyzx** [comment]
I'm sorry, but I would like to reopen this issue. Below is my deployment information:

Node: v20.12.1
Arch: x64
Platform: linux
Docker: true
RootDB: pg
PackageVersion: 0.251.1

I also encountered this issue in the built-in browser of a mobile application, which seems to be based on Chromium version 106, an older version.

The specific manifestations are as follows:

All the + buttons are displayed as "add".
In the dropdown menu of "Create View", grid_view, image, and view_kanban are displayed as icon names, while the calendar icon is displayed normally.
The expand icons for Base and Table are displayed as "chevron_right" instead of ">", but the expand icon for external databases displays normally.
The sidebar expand button is displayed as "menu".
The logout icon is displayed as its name.
The translate icon is displayed as its name.
The icons for all column names are displayed normally.
