### ISSUE TITLE
[FEATURE] limit attachments to upload

### ISSUE THREAD

**Issue by pixplix-user** [nocodb/nocodb#685]
A option where limit count attachments in column

**Comment by djmaze** [comment]
It is currently possible to DoS the NocoDB or the underlying server by uploading a very large attachment. At least when using Minio as a storage backend, it seems the complete attachment is loaded into memory before being uploaded to the storage backend. 

There should be an upload limit and, what's more, the attachment should be stored in a temporary file instead of staying completely in-memory during upload.

**Comment by dstala** [comment]
Marking as `duplicate`; will be tracked under https://github.com/nocodb/nocodb/issues/2905
