### ISSUE TITLE
permissions Precise to Fields

### ISSUE THREAD

**Issue by githubmyname** [nocodb/nocodb#6893]
### Please confirm if feature request does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

permissions Precise to Fields

### Suggested Solution

permissions Precise to Fields
Add, modify, find, delete

**Comment by dstala** [comment]
@githubmyname Field level permissions is in our roadmap & some of the earlier discussions cover it. Closing this issue & this request will be tracked under https://github.com/nocodb/nocodb/issues/5075
This issue is a subset of requests covered under
https://github.com/nocodb/nocodb/issues/4437
https://github.com/nocodb/nocodb/issues/4673
