### ISSUE TITLE
🐛 Bug: Webhook triggered by complicated formula multiple times before value was committed

### ISSUE THREAD

**Issue by fengjiongmax** [nocodb/nocodb#7256]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. create a base.
2. create a formula field referencing the `Name` field using formula `REGEX_REPLACE(REGEX_REPLACE(LOWER({Name}), "[\\?\\!_.,: ]", "-"), "-+", "-")`  
3. create a webhook with event `After Update`
4. update the value in `Name` and hit **Enter**

During step 4, before hitting **Enter**, if the value is very long, then a loading wheel will show up in the `#` column, and then the webhook will be triggered multiple times.

### Desired Behavior

Only when the value of the field referenced by the formula field was committed( in our case `Name`) will the formula field update, then triggering the webhook.

* by committed I mean hitting **Enter**, or the referenced field is not active( focused in front end term).

### Project Details

Node: **v18.18.2**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.202.10**

**Comment by dstala** [comment]
@fengjiongmax This is by design & multiple updates is due to de-bounce timer related auto save getting triggered & not related to formula. 

You can try using Expanded record to update cell value if you want to avoid de-bounce timer related multiple hook triggers. In case of expanded record, de-bounce timer remains disabled & the value fed into the cell are updated only on explicit `Save`

**Comment by fengjiongmax** [comment]
Great!
I didn't know the Expanded record, learned something new today, Thank you!
