### ISSUE TITLE
🐛 Bug: webhook trigger on triggering delete of selected records

### ISSUE THREAD

**Issue by dstala** [nocodb/nocodb#7511]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

webhook trigger when 
- multiple records are selected in one go & `Delete selected records` : bulk delete trigger
- one record is selected and `Delete selected records ` : bulk delete trigger

### Desired Behavior

for the latter case, it should be `delete` trigger instead of `bulk.delete`

### Project Details

204.0

**Comment by ZYG-130425** [comment]
Version: nocodb:0.204.0

Issue Reproduction Steps for Table Record Deletion Webhook:
1、Delete a single row with action: "Delete".
2、Delete multiple rows with action: Execute "Delete" multiple times.

Expected Behavior:
For the latter case, it should trigger a bulk.delete trigger instead of a regular delete.
