### ISSUE TITLE
🐛 Bug: Base reorder in `Mobile View`

### ISSUE THREAD

**Issue by rameshmane7218** [nocodb/nocodb#7582]
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- Instead of scrolling to bottom in mobile view sidebar, base is reording 

### Desired Behavior

Disable base reordering in mobile view

### Project Details

204.0

**Comment by johnmpost** [comment]
The fix for this **doesn't work** on larger touchscreens like tablets. The "mobile view" is solely based on viewport size, not touchscreen/mouse. Even in the latest version of NocoDB Cloud, **it is IMPOSSIBLE to scroll through base views on a tablet.** It just reorders the views.

Please get this fixed.
