### ISSUE TITLE
🔦 Feature: Improve UX related to clicking LTAR, rows drag and drop

### ISSUE THREAD

**Issue by kdamsmt** [nocodb/nocodb#7700]
### Please confirm if feature request does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Describe the usecase for the feature

Today is UI/UX if our software get bad on it or hard to used it won't grow on open source idea.

### Suggested Solution

ex: supabase is open source to firebase than supabase design ui/ux and performance really better than firebase.

**Comment by salim-b** [comment]
This feature request is so hollow, it should just be closed IMHO.

**Comment by asasn** [comment]
At present, there are really big flaws in UI, developers do not seem to pay much attention to user interaction experience, or the workload is too large, and it is not enough to put it on the agenda for the time being...
However, software engineering is made up of human and machine interactions, and I would recommend taking a good look at airtable or notion's UI and interactive approach, so that you can catch up with the identity of the next.
The simplest example is that multiple Links can't be clicked directly to similar,Such a way to show multiple Links...
![image](https://github.com/nocodb/nocodb/assets/48091517/b45b60e8-5c40-4bcf-a128-5e86abd71614)

Record heads, on the other hand, lack a similar way to drag and move.
![image](https://github.com/nocodb/nocodb/assets/48091517/9ee8cc52-2917-48ae-92dd-e0430eb91b9e)

And, uh, the present
![image](https://github.com/nocodb/nocodb/assets/48091517/664ab0cf-c1ea-4f23-bcde-5f94ea7fb00e)

Line number, the width here is too high...
One small detail after another, like a trickle, converges into a river, which adds up to the entire user experience.
There are many similar, in fact, compared with the products of those large commercial companies can be seen, they are so designed, not for no reason.

With all due respect, this is not an empty function request, but the current work in this area is indeed relatively simple, and the developers may be biased towards the technical faction.
This should also be the drawback of many open source free projects, in terms of user interaction.
**If ethical and legal issues are put aside, I personally believe that we should first copy mature products UI 1:1 and then seek innovation.**

**Comment by dstala** [comment]
Rows drag drop will be tracked in separate PR. minor corrections to the UI have been taken up.
