### ISSUE TITLE
[Feature] Select all records from a table

### ISSUE THREAD

**Issue by alexandregrignon** [nocodb/nocodb#817]
**Need for this feature**
Ability to select all records from a table. For example, to delete all records.

**Is your feature request related to a problem? Please describe.**
From now it is only possible to select records one by one. 

**Describe the solution you'd like**
Checkbox on top of "#" column.

**Describe alternatives you've considered**
"Select all" button.
Multi select of rows with shift button.

**Additional context**
No.

**Comment by pranavxc** [comment]
Added in `0.83.6`

**Comment by mmospanenko** [comment]
Doesn't work - it selects only loaded (visible) records.

**Comment by ArneNostitz** [comment]
how does one select all? cmd+a does nothing, holding shift does nothing ... i can only click one at a time. there is no checkbox on the header to select all ... any help is welcome

**Comment by jln-dk** [comment]
Agree with @ArneNostitz here. I'm on version 0.258.3 and the "toggle all" checkbox is gone, you can't do Cmd+A or anything like that you would expect. It's very cumbersome to delete many rows at once, because you have to select them one by one manually.

Please consider reopening this issue. @pranavxc
