### ISSUE TITLE
🐛 Bug: PK not saving properly when adding row through UI

### ISSUE THREAD

**Issue by k29fan** [nocodb/nocodb#8351]
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Make a new project
2. From script, create a table with a PK with the following column fields:
```
headers = {
        "xc-auth": "auth here",
        "Content-Type": "application/json"
    }

url = "url here"

table = {"title": "test",
         "table_name": "test",
         "columns": [{
            "column_name": "PK",
            "title": "PK",
            "uidt": "SingleLineText",
            "dt": "character varying",
            "pk": 1
}]}

res = json.dumps(table)

print(requests.post(url, data=res, headers=headers).json())
```
3. Try to add rows with new primary key values (Try adding 'Great Western Canada' and variations of it, it results in the UI showing shortened versions of what you entered)

### Desired Behavior

To save each row properly

### Project Details

Node: **v16.19.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **pg**
PackageVersion: **0.108.1**

**Comment by HassanShakerIsmail** [comment]
Was able to reproduce on same system - seems like an onkeyup listener event is firing too quickly during entry of data into pk column which causes premature upsert into db. Short text entries in pk column typed at moderate pace (such that listener event doesn't fire before you're done entering data) seems to avoid this issue. 

i'm thinking nocodb's lack of being able to retroactively edit PK's coupled with the premature upsertion because of the listener event firing is causing data to be half uploaded depending on whatever the listener event saw at the time of firing.

Tables without a pk (and hence columns that can be retroactively edited) seem to avoid the issue completely, can anyone else verify? Still new to nocodb so a little hesitant to trust my conclusion here..

**Comment by dstala** [comment]
fixed here
https://github.com/nocodb/nocohub/commit/b6adcab79f1f33f5638be8e470bde4f3ef1aca92

should be available in OSS in next release

**Comment by HassanShakerIsmail** [comment]
> fixed here https://github.com/nocodb/nocohub/commit/b6adcab79f1f33f5638be8e470bde4f3ef1aca92
> 
> should be available in OSS in next release

thanks for the quick work though
i think commit link is broken, any idea when next release might happen?
