### ISSUE TITLE
Bug : Audit records only available for super user ? 

### ISSUE THREAD

**Issue by PyT** [nocodb/nocodb#8793]
Hello,

I'm hosting a version of Nocodb on my server (windows). 
The audit records feature is very useful but it seems that it's only accessible to the super user of the database. 
Am I right ? 
or is there anyway to authorize all users to see the audit records of all records on datatable ? 

Thanks for your help,

Pierre-Yves

**Comment by dstala** [comment]
@PyT Audit logs (including record audits) are available to users with creator access & above. 
Currently, you will have to invite your users with `creator` role to provide access to audit logs

**Comment by PyT** [comment]
hey thx @dstala for your answer
that's what I read in the doc but for below rights : 
![image](https://github.com/nocodb/nocodb/assets/2209649/f6ba82b7-0b0d-4732-8afd-c4b585f2d723)

Vince cannot see records even if he has creator role : 
![image](https://github.com/nocodb/nocodb/assets/2209649/abc33b0d-c0b3-4585-9fa3-ebf16daecd53)

and PyT is able to see the records:
![image](https://github.com/nocodb/nocodb/assets/2209649/e60ed487-815b-4393-8a3d-7faeb5cf9679)

**Comment by PyT** [comment]
We did some test by running multiple instance with multiple "super admin" users
it seems that only the user with "super admin" right is able to see audit records. 

Does it ring a bell ?

**Comment by vcavallino** [comment]
Hello,

I do confirm what my colleague described. I've set up another instance of nocodb on my own, with three users: 
 - Super Admin (SA), with the viewer role on the base
 - User Jane Doe (JD), the owner of the base
 - User Paul Smith (PS), a user with the editor role on the base

SA cannot create/edit a record (expected since he has a view role), he can see the Audits detail of a record (surprising!) and he can access the Audit Log of the base (expected since he is SuperAdmin)

JD can create/edit/delete a record (expected), he cannot see the Audits detail of a record (surprising!) and  he can access the Audit Log of the base (expected since he the owner).

PS can create/edit/delete a record (expected), he cannot see the Audits detail of a record and  he cannot access the Audit Log of the base (expected).

I hope it helps understanding our issue.

**Comment by dstala** [comment]
Thanks for the details @PyT @vcavallino 
Will try & follow up on this
